{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from jira.client import JIRA\n",
    "from requests_toolbelt import user_agent\n",
    "from datetime import date,datetime\n",
    "from deep_translator import GoogleTranslator\n",
    "import pickle\n",
    "import pandas as pd\n",
    "from catboost import CatBoostClassifier\n",
    "import threading"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "options = {'server': \"https://hibernate.atlassian.net/\"}\n",
    "\n",
    "jira = JIRA(options, basic_auth=(\"bahriahmed94@gmail.com\", \"slHGJreyEZ1GCec8ZKbtEC6E\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def get_issues_by_type_jira(project,jira,initial,data,types,test):\n",
    "    \n",
    "    last_ticket=\"\"\n",
    "    test=False\n",
    "    \n",
    "    size = 100\n",
    "    \n",
    "        \n",
    "    \n",
    "    \n",
    "    for i in range(10):\n",
    "        start= initial*size\n",
    "        issues = jira.search_issues('project={}'.format(project),  start,size)\n",
    "        initial+=1\n",
    "        if len(issues) == 0:\n",
    "            test=True\n",
    "            break\n",
    "        \n",
    "        else :\n",
    "            if(not test):\n",
    "                test=True\n",
    "                last_ticket=issues[0].key.split(\"-\")[1]\n",
    "\n",
    "            for issue in issues:\n",
    "                \n",
    "                if(issue.fields.issuetype.name not in types):  \n",
    "                    types.append(issue.fields.issuetype.name)\n",
    "                    data[issue.fields.issuetype.name]=0\n",
    "                    \n",
    "            for issue in issues:\n",
    "                    data[issue.fields.issuetype.name]+=1\n",
    "\n",
    "    return data , last_ticket"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def splitJ(data):\n",
    "    threads=[]\n",
    "    types=[]\n",
    "    i=0\n",
    "    test=False\n",
    "    while True:\n",
    "    \n",
    "        threads.append(threading.Thread(target=get_issues_by_type_jira,args=(\"HHH\",jira,i,data,types,test) ) )\n",
    "        threads[-1].start()\n",
    "        i+=10\n",
    "        if(test):\n",
    "            break\n",
    "\n",
    "    for t in threads:\n",
    "        t.join()\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: hibernate.atlassian.net. Connection pool size: 10\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 19.060036701813083s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 1.353177282966045s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=515000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/search\n",
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 8.479495946002796s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 12.756029950133382s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 4.188236733498892s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 16.465541205692386s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 17.855367657636037s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 17.374277743318153s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 7.125650436408179s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=515000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/search\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/search, will retry [1/3] in 10.602210117651298s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=515000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 5.611418641347498s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 10.242491624996626s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 7.1736930711675395s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 2.318295108667603s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 5.608129367034033s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 2.3845181276344785s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 3.1941484640946682s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 7.990718035611344s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=520000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/search\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=520000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/search\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/search, will retry [1/3] in 13.886041249681298s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=520000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=710000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/search\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) while doing GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=710000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/search\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 9.584050058793249s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 17.13927866404115s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 4.97480754053835s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 8.000972449603491s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 7.242610474038676s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))] errno:None on GET https://hibernate.atlassian.net/rest/api/2/field\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "{'response': None, 'request': <PreparedRequest [GET]>}\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 14.246375332120333s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 3.83458570116457s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 15.711026592181467s. Err: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/search, will retry [1/3] in 10.886206630165393s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/search?jql=project%3DHHH&startAt=710000&validateQuery=True&maxResults=100 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 5.898763651453578s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 2.845008682134258s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n",
      "WARNING:root:Got recoverable error from GET https://hibernate.atlassian.net/rest/api/2/field, will retry [1/3] in 12.489898864266003s. Err: HTTPSConnectionPool(host='hibernate.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/field (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))\n"
     ]
    }
   ],
   "source": [
    "data=dict()\n",
    "splitJ(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'Task': 124,\n",
       " 'Bug': 529,\n",
       " 'Improvement': 251,\n",
       " 'Sub-task': 32,\n",
       " 'Remove Feature': 9,\n",
       " 'New Feature': 45,\n",
       " 'Deprecation': 6,\n",
       " 'Story': 3,\n",
       " 'Epic': 1}"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_issues_by_type_jira(project,jira):\n",
    "    data=dict()\n",
    "    last_ticket=\"\"\n",
    "    test=False\n",
    "    types=[]\n",
    "    size = 100\n",
    "    initial = 0\n",
    "    while True:\n",
    "        start= initial*size\n",
    "        issues = jira.search_issues('project={}'.format(project),  start,size)\n",
    "        if len(issues) == 0:\n",
    "            break\n",
    "        initial += 1\n",
    "\n",
    "        if(not test):\n",
    "            test=True\n",
    "            last_ticket=issues[0].key.split(\"-\")[1]\n",
    "\n",
    "        for issue in issues:\n",
    "            \n",
    "            if(issue.fields.issuetype.name not in types):  \n",
    "                types.append(issue.fields.issuetype.name)\n",
    "                data[issue.fields.issuetype.name]=0\n",
    "                \n",
    "        for issue in issues:\n",
    "                data[issue.fields.issuetype.name]+=1\n",
    "\n",
    "    return data , last_ticket"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "ae=get_issues_by_type_jira(\"HHH\",jira)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "({'Task': 1279,\n",
       "  'Bug': 9082,\n",
       "  'Improvement': 3014,\n",
       "  'Sub-task': 380,\n",
       "  'Remove Feature': 37,\n",
       "  'New Feature': 937,\n",
       "  'Deprecation': 60,\n",
       "  'Story': 5,\n",
       "  'Epic': 3,\n",
       "  'Patch': 263,\n",
       "  'Technical task': 8},\n",
       " '15226')"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ae"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "16d5d8e9511b4a1f70ac14e2fd6fdd3dfeaec2e7924ea268b32083e775082e72"
  },
  "kernelspec": {
   "display_name": "Python 3.9.9 ('env': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.9"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
